#* @implicitly included *#
#* @vtlvariable name="deleteLink" type="java.lang.String" file="trial-request.ftl" *#
#* @vtlvariable name="approveLink" type="java.lang.String" file="trial-request.ftl" *#
#* @vtlvariable name="comment" type="java.lang.String" file="trial-request.ftl" *#
#* @vtlvariable name="region" type="com.infor.cloudsuite.entity.Region" file="trial-request.ftl" *#
#* @vtlvariable name="user" type="com.infor.cloudsuite.entity.User" file="trial-request.ftl" *#
#* @vtlvariable name="product" type="com.infor.cloudsuite.entity.Product" file="trial-request.ftl" *#
#* @vtlvariable name="proxyUrl" type="java.lang.String" file="trial-confirmation.ftl" *#
#* @vtlvariable name="trialsLeft" type="java.lang.Integer" file="trials-low.ftl" *#
#* @vtlvariable name="productName" type="java.lang.String" file="trials-low.ftl" *#
#* @vtlvariable name="productName" type="java.lang.String" file="trials-gone.ftl" *#
#* @vtlvariable name="resetUrl" type="java.lang.String" file="password-reset.ftl" *#
#* @vtlvariable name="firstName" type="java.lang.String" file="password-reset.ftl" *#
#* @vtlvariable name="product" type="com.infor.cloudsuite.entity.Product" file="trial-confirmation.ftl" *#
#* @vtlvariable name="trialDto" type="com.infor.cloudsuite.dto.TrialDto" file="trial-confirmation.ftl" *#
#* @vtlvariable name="dto" type="com.infor.cloudsuite.dto.BuyConsultDto" file="product-consult.ftl" *#
#* @vtlvariable name="product" type="com.infor.cloudsuite.entity.Product" file="product-consult.ftl" *#
#* @vtlvariable name="secUser" type="com.infor.cloudsuite.platform.security.SecurityUser" file="product-consult.ftl" *#
#* @vtlvariable name="activationUrl" type="java.lang.String" file="registration-email.ftl" *#
#* @vtlvariable name="firstName" type="java.lang.String" file="registration-email.ftl" *#
